name: Deploy

on:
  workflow_dispatch:

env:
  SERVER_HOST: 89.169.3.89
  SERVER_USER: root
  SERVER_PATH: /root/project

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.MY_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Generate known_hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Sync project files to server
        shell: bash
        run: |
          rsync --archive --compress --delete --progress \
            --exclude=".env" \
            ./ ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}

      - name: Copy default photo none.png separately
        shell: bash
        run: |
          rsync --archive --compress ./django-server/media/users/none.png ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}/django-server/media/users/

      - name: Run docker-compose on server
        shell: bash
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << EOF
            set -e
            cd ${{ env.SERVER_PATH }}
            docker compose pull               
            docker compose up --build -d      
          EOF
